### ISSUE TITLE
Cookies bar

### ISSUE THREAD

**Issue by literakl** [literakl/mezinamiridici#125]
Implement a bar at bottom of page with a cookie allowance. Choice checkboxes: All / Statistical / Marketing. When All is set then set all other checkboxes. When Statistical or Marketing are unset, unset All too.

Put some dummy explanation text and a link to Privacy policy (URL TBD). Use resource bundle (en.json).

Get inspired on internet. It must be non intrusive and rather small.

Selection will be saved to local storage - date when user submitted the form.

**Comment by literakl** [comment]
Design:

I will write a Page in CMS call Privacy information. Its link will be /privacy.

- [ ] create a link in header under Information menu: Privacy
- [ ] create new pop over displaying cookies options - similar to Slack.com. There shall be a link to Privacy page too. If the user selects Cookie settings button, display new popover similar to Slack. All texts will be hard coded, no resource bundles (except buttons).
- [ ] insert a link in header under Information menu: Cookie settings

![image](https://user-images.githubusercontent.com/6383287/115157638-a17a2600-a08a-11eb-9b8c-cdfb5f6bbed0.png)
![image](https://user-images.githubusercontent.com/6383287/115157659-bbb40400-a08a-11eb-866f-d794782dbec8.png)

**Comment by hasankhan01** [comment]
Added and pushed

**Comment by literakl** [comment]
![image](https://user-images.githubusercontent.com/6383287/115770128-9423ab00-a3ac-11eb-9a45-fd8b7d7b3675.png)

**Comment by literakl** [comment]
Date of user consent and his choices must be stored in localStorage. If it is empty, show these cookies bars again. User can show the dialog again from the menu - overwriting the values.

Business logic will be handled later.

**Comment by literakl** [comment]
- [ ] load cookies setting must be in vuex store
- [ ] replace dummy text

**Comment by literakl** [comment]
GTM must be initialized properly:

- https://support.google.com/analytics/answer/9976101?hl=en
- https://www.iubenda.com/en/help/27137-google-consent-mode
- https://www.simoahava.com/analytics/consent-settings-google-tag-manager/

**Comment by literakl** [comment]
I do not see any change in Network tab once I update cookie settings. GTM queue seems legit:
![image](https://user-images.githubusercontent.com/6383287/145086362-ba5f3798-200b-4d13-b38b-b8075a5859ad.png)

**Comment by literakl** [comment]
Relevant information: https://stackoverflow.com/questions/70266113/no-analytics-cookies-is-set-upon-a-consent-was-updated

**Comment by literakl** [comment]
cookie close button does not work, is the handler implemented?

**Comment by literakl** [comment]
fixed, it was broken once Modify cookie functionality was added
