### ISSUE TITLE
Discussion form disappeared for unsigned users

### ISSUE THREAD

**Issue by literakl** [literakl/mezinamiridici#137]
Some code broken discussions in blog for unsigned users. 

![image](https://user-images.githubusercontent.com/6383287/112200291-601f6380-8c0f-11eb-89e0-e183ec797264.png)

![image](https://user-images.githubusercontent.com/6383287/112200328-6b728f00-8c0f-11eb-9c6e-2ba26194425b.png)

**Comment by literakl** [comment]
see the git history, I expect a merging mistake

**Comment by donatelloraphael** [comment]
Is this about the lack of tiptap editor for unsigned users? It is currently disabled for them since trying to reply without signing in now throws an error. I fixed another minor bug that showed wrong comments when using browser back button.

**Comment by literakl** [comment]
Compare with beta.mezinamiridici.cz

Dne po 29. 3. 2021 3:25 uživatel donatelloraphael ***@***.***>
napsal:
