### ISSUE TITLE
Picture upload changes

### ISSUE THREAD

**Issue by literakl** [literakl/mezinamiridici#145]
Store absolute URL without host.
Store a reference in Mongo (linked item, mime type, location)

**Comment by literakl** [comment]
TODO: 
- find a way to set itemId for pictures uploaded during create action
- it seems unrealiable, POST request is not sent sometimes, Editor content was deleted once
- something sends old /uploadImage URL preflight option
- update Pages too

**Comment by kotte-sanya** [comment]
It is completed and waiting in "145-picture-upload-changes".

**Comment by literakl** [comment]
UX trouble: no indication that something happens once user submits the dialog. Please add some indirect progress bar and handle errors (Submit failed).

**Comment by literakl** [comment]
tested - elegant solution 👍 
eslint troubles - have you set it up?
other comments in the last commit

**Comment by literakl** [comment]
Please add a visual feedback to user about ongoing upload. User has no clue if the upload has taken a place until the upload is finished. This can be frustrating / misleading for lage images or slow networks.

Btw can you detect the file size within a SPA before upload? It makes sense to implement a (confiurable) size limit.

**Comment by kotte-sanya** [comment]
Implemented image upload progress bar and file type validation.
waiting in #145 branch.

**Comment by literakl** [comment]
1. the progress bar is shown on fast internet for a very small time, then there is a bigger time waiting for a picture. I think that inserting a dummy image placeholder would make better UX.
2. if the internet speed is reduced (aka 10 Mbps - network throttling in Chrome dev), the page tries to reload many times but it gets cancelled. There is a progress bar. Once upload completes, the page reloads again and all work is lost!

![image](https://user-images.githubusercontent.com/6383287/115121467-31e53780-9fb3-11eb-9fbc-41c72a2735e5.png)

https://user-images.githubusercontent.com/6383287/115121491-5214f680-9fb3-11eb-9776-f022bdc3aafa.mov

**Comment by literakl** [comment]
/novy initiator (failed)
![image](https://user-images.githubusercontent.com/6383287/115141269-9946ca00-a03b-11eb-900a-4c2657e339a5.png)

**Comment by literakl** [comment]
No error indication:
![image](https://user-images.githubusercontent.com/6383287/115275379-02b10080-a142-11eb-92cd-48475b200b34.png)

Server responded with: 413 Request Entity Too Large

We shall have a picture length check in frontend.

No indication when user selects an unsupported file format. Is it possible to configure select file box with required suffixes?

**Comment by literakl** [comment]
Maximum file size is 6 MB now (nginx). If reach, this is an unhandled error:

IMAGE_UPLOAD
xhr.js:177 POST https://beta.mezinamiridici.cz/api/v1/images 502
dispatchXhrRequest @ xhr.js:177
Promise.then (async)
request @ Axios.js:61
post @ api.js:55
_callee14$ @ items.js:142
tryCatch @ runtime.js:62
invoke @ runtime.js:296
prototype.<computed> @ runtime.js:114
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
UPLOAD_IMAGE @ items.js:136
_callee2$ @ Editor.vue:153
(anonymous) @ Editor.vue:276
Show 7 more frames
createError.js:16 Uncaught (in promise) Error: Request failed with status code 502
    at createError (createError.js:16)
    at settle (settle.js:17)
    at XMLHttpRequest.handleLoad (xhr.js:62)

Reload page does not occur here, it was a really vue-cli error.

**Comment by literakl** [comment]
checks added
