### ISSUE TITLE
Site visit analytics

### ISSUE THREAD

**Issue by literakl** [literakl/mezinamiridici#169]
Google tag manager is more convinient but I would stick with plain GA JS script to mimize 3rd party cookies

Alternatives:
- https://matomo.org/pricing/  0 for self hosted + plugins, 1M page view for 239€ including plug ins
- https://usefathom.com/pricing $14/month for 100K, $34 for 400K, $54 for 1M page views

**Comment by LabN36** [comment]
matomo is installed and integrated.
[know more about on how does matomo count unique visitor] https://matomo.org/faq/general/faq_43/

**Comment by literakl** [comment]
Please write here the setup here. E.g. which server and which software is used, if they are dockerized and how it is started. Thanks

**Comment by literakl** [comment]
After some tests showing strange results and lacking setup information I switched to GA
