### ISSUE TITLE
Create PM2 configuration for all scripts

### ISSUE THREAD

**Issue by literakl** [literakl/mezinamiridici#174]
There are many jobs backend/src/jobs and main app. Create configs that can be fine tuned and easier maintained than CLI.  Set easy to remember names, e.g. backend.

**Comment by literakl** [comment]
See the docs: https://pm2.keymetrics.io/docs/usage/application-declaration/#yaml-format

Main app + all scripts need a configuration. I do not want to specify that in CLI.

**Comment by literakl** [comment]
the port must be configurable:

app.listen(3000, () => logger.info('Server started'));

**Comment by LabN36** [comment]
pm2 is configured on backend. there is a file named `ecosystem.config.js` under **backend** directory.
1. we can change `port number `in this directory 
2. along with api server there are 2 more scripts are running(`CalculateUserRanks` & `ParseAccidents`)

Note: `CreateSitemap` script is not configured as of now, this script will reside on www

**Comment by literakl** [comment]
PM2 interfers with log4js-node library so no logs are created. pm2: true in logging config helps but I need to ensure that it works in a cluster mode with more processes.
