### ISSUE TITLE
Upgrade Vue + CLI tools

### ISSUE THREAD

**Issue by literakl** [literakl/mezinamiridici#37]
@vue/cli-plugin-pwa": "^3.12.1" -> 4.2.3
@vue/eslint-config-airbnb 4.0.0 -> 5.0.2

**Comment by literakl** [comment]
Vue upgraded to 2.6.12. Router, Vuex and CLI are waiting.

**Comment by kotte-sanya** [comment]
upgraded vue-router, vuex and vue-cli tools packages.
waiting in 145-picture-upload branch

**Comment by literakl** [comment]
Unless neccessary use separate branch for each individual issue.

**Comment by literakl** [comment]
Why did you downgrade these packages?

    "vue-authenticate": "^1.4.1",
    "vue-authenticate": "^1.3.4",

    "gulp": "^4.0.2",
    "gulp": "^3.9.1",

Why have I started getting this warning? What package shall I update? Node itself?

npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

**Comment by literakl** [comment]
new console warning:

vue-router.esm.js:16 [vue-router] <router-link>'s event prop is deprecated and has been removed in Vue Router 4. Use the v-slot API to remove this warning: https://next.router.vuejs.org/guide/migration/#removal-of-event-and-tag-props-in-router-link.

Fix it please

**Comment by literakl** [comment]
Pham:

I have checked after upgrade it. But when I ran 'npm audit fix' ,  two package was downgrade. 
Also the "@vue/cli-plugin-babel" package can't upgrade to latest version. When it was upgraded, occur a lot errors.

**Comment by kotte-sanya** [comment]
fixed the vue-router warning.
the cause is that dropdown-item of bootstrap-vue are using old version of vue-router,

**Comment by literakl** [comment]
gulp failed with "ReferenceError: primordials is not defined". This is a side efect of the downgrade. I have upgraded back to 4.0.2.

https://timonweb.com/javascript/how-to-fix-referenceerror-primordials-is-not-defined-error/
