### ISSUE TITLE
Comments prototype

### ISSUE THREAD

**Issue by literakl** [literakl/mezinamiridici#43]
Create new feature branch and implement following prototype (it can be quick and dirty)

GUI to display the comments including paging if there is more than 100 comments (solution / load 101 comments from DB. If server returns 101, then this is an indicator of new page)

There will be maximum depth 2 - comment and its replies

Update load test data generator
https://github.com/literakl/mezinamiridici/blob/master/infrastructure/doc/item_poll.json

**Comment by LabN36** [comment]
please review [feature branch](https://github.com/literakl/mezinamiridici/tree/feature), once you're okay I'll create a pull request.
