### ISSUE TITLE
Add bio and registration date to profile

### ISSUE THREAD

**Issue by literakl** [literakl/mezinamiridici#47]
bio - introductory text
registration date - how long the user is member

**Comment by literakl** [comment]
verify XSS protection

**Comment by literakl** [comment]
Hassan, please sketch up a prototype with bio on a profile view page. E.g. a free text where user can tell something about him (2000 chars max or less)

**Comment by hasankhan01** [comment]
Sure I am thinking about it. There is also need to add textarea for bio in edit profile page.. I think what you say?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by literakl** [comment]
Please add a display and review textarea afterwards.

**Comment by literakl** [comment]
Profile.vue megred to master
