### ISSUE TITLE
Support for anchors

### ISSUE THREAD

**Issue by literakl** [literakl/mezinamiridici#51]
I need the links to anchors, e.g. comments. They must focus the selected id either from a router link or when passed in URL.

This is so far the best option: https://vue-scrollto.netlify.app/docs/

in the component:
```
  mounted() {
    if (window.location.hash === this.$route.hash) {
      const el = document.getElementById(this.$route.hash.slice(1));
      if (el) {
        this.$scrollTo(this.$route.hash);
      }
    }
  },
```

but it is far from perfect. I need a simple solution that works everywhere with global setup and it is compatible with the router link.

Alternate solutions that do not work for me:

https://stackoverflow.com/questions/45201014/how-to-handle-anchors-bookmarks-with-vue-router
https://forum.vuejs.org/t/how-to-handle-anchors-bookmarks-with-vue-router/14563/5
https://techformist.com/remember-position-history-navigate-anchors-vue/
https://www.npmjs.com/package/vue-scrollto - useful library

I have not tried:

https://github.com/mperator/vue-anchor-router-link#readme

How is Vue documentation implemented? Anchors work well: https://vuejs.org/v2/guide/#Declarative-Rendering

**Comment by kotte-sanya** [comment]
Hello.
Let's try with the following code in the Comments.vue file.

    mounted() {
      const { hash } = this.$route;  
      if (this.$route.hash) {
          setTimeout(() => { window.location.href = hash; }, 1000);
      }
    }

**Comment by literakl** [comment]
merged changes, added a link to poll comments
