### ISSUE TITLE
Contribution activity

### ISSUE THREAD

**Issue by literakl** [literakl/mezinamiridici#77]
User profile will hold a stream of user activity: comments, votes, upvotes. Poll votes only when the profile is active or poll has multiple votes.
![image](https://user-images.githubusercontent.com/6383287/90307724-48456b80-ded9-11ea-89f4-139eb53489ad.png)

**Comment by literakl** [comment]
Ignore a vote in a poll where the current user is the only voter and he does not share his profile. Because otherwise any visitor would be able to find his profile settings with Analyze votes feature.

**Comment by literakl** [comment]
Create a collection user_activity. Common part:

- id
- userId
- published (date)
- itemId
- action: create, vote, comment

Comment specific part:

- commentId
- vote (1, -1) - only when action is vote

Poll specific part:

empty

**Comment by literakl** [comment]
https://github.com/naver/egjs-infinitegrid this component can be used in other sections later
GUI does not need to mimic the attached screenshot. There shall be one item per line. Text only.

**Comment by kotte-sanya** [comment]
replaced vertical timeline with infinitegrid component.

**Comment by literakl** [comment]
merged, but there is still work to be done

**Comment by literakl** [comment]
basic implementation done
