### ISSUE TITLE
Item component

### ISSUE THREAD

**Issue by literakl** [literakl/mezinamiridici#83]
Create a component <showItem :item="poll"/> that will display any kind of item: poll, blog.

The common part will be a bold caption and stream picture. Then there will be in footer:

- poll: date, X votes, Y comments, last Z
- blog: date, author, Y comments, last Z

Design inspiration:

![image](https://user-images.githubusercontent.com/6383287/90973164-ac8ead80-e51f-11ea-83bf-9d85d75293c0.png)

Use this component on Home.vue and Tag.vue.

**Comment by kotte-sanya** [comment]
Fixed create/update/view blog. Added item view component and item list component.

**Comment by literakl** [comment]
merged
