### ISSUE TITLE
Editorjs i18n

### ISSUE THREAD

**Issue by literakl** [literakl/mezinamiridici#84]
Console has errors. We shall supply localized texts: https://editorjs.io/internationalization

**Comment by kotte-sanya** [comment]
Fixed editorjs i18n. But can't remove console errors.
https://github.com/codex-team/editor.js/issues/1269#issuecomment-673709334

**Comment by literakl** [comment]
Does the console error occur in a production build too?

**Comment by literakl** [comment]
merged
