### ISSUE TITLE
Parse car accidents stats

### ISSUE THREAD

**Issue by literakl** [literakl/mezinamiridici#87]
Implement a scheduled job infrastructure/src/jobs/parseAccidents.js that will parse police records.

env ACCIDENTS_RECORDS_URL = https://aplikace.policie.cz/statistiky-dopravnich-nehod/default.aspx
env ACCIDENTS_RECORDS_CRON = 6 AM each day
enc ACCIDENTS_RECORDS_RETRY = 10 (minutes)

If there are records for the selected day, store them in accidents collection defined in infrastructure/doc/accidents.json. To test non existing values, use future day or 01. February 2009. Data starts at 10. february 2009.

If there are no records for the selected day, calculate next scheduled time as now + ACCIDENTS_RECORDS_RETRY and pass it into schedule method instead of the cron expression and run the parse method again.

Log the execution of the job in job-accidents.log - start, finish and if it saved data or data were missing. Plus exceptions if they occur.

Technically use Axios to fetch data (POST with body) and https://cheerio.js.org/ to parse the table (https://www.npmjs.com/package/cheerio-advanced-selectors might be helpfull too).

There will be two methods:

`parseData` loads data, saves them and returns true or returns false when data is missing or cannot be parsed or saved
`scheduleParsing` calls the `parseData` method with the current day as an argument and it eventually fires new one time occurence of itself in future if the `parseData` returned false

The `parseData` method must be exported because I will call it manually from command line to parse old data.

**Comment by literakl** [comment]
https://pusher.com/tutorials/web-scraper-node - there is a sample project for Cheerio, it may help you

**Comment by kotte-sanya** [comment]
Added accidents compare blog.

**Comment by literakl** [comment]
merged

**Comment by literakl** [comment]
finished
