### ISSUE TITLE
Use editorjs for comments

### ISSUE THREAD

**Issue by literakl** [literakl/mezinamiridici#89]
The current solution is using plain textarea without any formatting with a button to add emoji. This approach does not allow quotations and the inline emoji button makes the textarea unusable on a mobile phone.

- use editorjs in CommentForm.vue (with v-if, so it is created on demand), remove obsolete styles
- create a simple inline plugin for displaying emoji select box, see https://github.com/codex-team/editor.js/issues/1263
- take styles from BlogForm, the border is neccessary for better UX
- remove markdown parser from createComment and package.json
- update createComment, convert internal JSON format to HTML. Save the source.
- update getComments, filter out source using projections
- update comment.int.test.js, we need to send internal JSON and retrieve HTML. The test must pass.
- update generateSameData.js, we need to send internal JSON.

**Comment by kotte-sanya** [comment]
Replaced editorjs with textarea in comment.
Changed insert Emoji feature.

**Comment by literakl** [comment]
merged
