### ISSUE TITLE
Internal CMS

### ISSUE THREAD

**Issue by literakl** [literakl/mezinamiridici#93]
Create new object with the following attributes:
- type (values: help, content)
- info.caption
- info.slug
- info.date (optional)
- info.published
- data.content
- info.picture (optional)
- info.tags (optional)

Create CRUD for this object for a user with cms:admin role. Sanitize HTML code. Slug is entered by user, not generated). Edit page will contain a big textarea, not WYSIWYG editor.

Create Vue file for URL /c/:slug (for `content` type) and /h/:slug (for `help` type) that will find the content for the specified URL by the slug parameter and display it. The screen will display h2>info.caption/h2> and data.content as raw HTML.

Items with type `help` will filtered out by backend in /v1/item-stream and /bff/items/:tag

**Comment by kotte-sanya** [comment]
Added Internal CMS feature.

**Comment by literakl** [comment]
merged, renamed CMS to content, fixed URIs

**Comment by literakl** [comment]
TODO: 
- check that slug does not start with /
- quote content in textarea so edit of HTML text does work
