### ISSUE TITLE
Reduce app size with tree shaking

### ISSUE THREAD

**Issue by literakl** [literakl/mezinamiridici#95]
https://github.com/webpack-contrib/webpack-bundle-analyzer

spa/vue.config.js
const { BundleAnalyzerPlugin } = require('webpack-bundle-analyzer');
module.exports = {
    plugins: [
      new BundleAnalyzerPlugin(),
    ],
  },

Then start app and open http://127.0.0.1:8888/

Current stats are at #20 
![image](https://user-images.githubusercontent.com/6383287/93373980-64308a00-f856-11ea-9ba3-c4f0e50f0e30.png)

**Comment by literakl** [comment]
https://github.com/jmblog/how-to-optimize-momentjs-with-webpack - reduce locales (we may eventually use cs and en locales in ChartJS, maybe)

**Comment by literakl** [comment]
Bootstrap vue needs to do ES import of individual components instead of complete library: 
https://github.com/bootstrap-vue/bootstrap-vue/issues/3468
https://dev.to/m9hmood/reduce-vue-js-application-size-kfl

**Comment by literakl** [comment]
Tree shaking works only for ES6 modules. At least it's true for Webpack and I suppose for rollup as well. Your first definition is ES6, second is commonjs.
https://stackoverflow.com/a/53363913/1639556

**Comment by kotte-sanya** [comment]
Upgraded chart.js to V3.0 beta and was removed the moment.js
Reduced js size from 2.31MB to 2.22MB

**Comment by literakl** [comment]
File                                                          Size             Gzipped
  dist\js\app.94e1eb91.js                1626.37 KiB           396.71 KiB
  dist\js\blog-chunk.9765b2d4.js   192.13 KiB             53.13 KiB
  dist\js\poll-chunk.136fb541.js     160.77 KiB             44.88 KiB
  dist\js\cms-chunk.2e60b4c3.js    156.90 KiB             43.68 KiB
  dist\js\user-chunk.a961cacd.js    123.10 KiB             23.85 KiB
  dist\js\site-chunk.b2c7ae80.js     15.17 KiB               5.60 KiB
  dist\precache-manifest.a434cd588db1286807c7078e7a8a5b26.js    5.10 KiB                                                                                    1.84 KiB
  dist\service-worker.js                  0.95 KiB                 0.54 KiB

It is strange the the original sum of all files before optimizations was 1986 KB and it is 2280 KB now.

**Comment by literakl** [comment]
vuejs-datepicker and boostrap icons seem large
![image](https://user-images.githubusercontent.com/6383287/93636468-49941780-f9f4-11ea-9d79-504e0fa029e6.png)

**Comment by literakl** [comment]
1858 KB with mode production

dist\js\app.cb54cc6d.js | 1369,16 KiB | 361,2 KiB
dist\js\content-chunk.dbf7c0b4.js | 261,38 KiB | 77,18 KiB
dist\js\user-chunk.b9f2ba19.js | 120,95 KiB | 23,1KiB
dist\js\admin-chunk.e345be83.js | 101,28 KiB | 25,29 KiB
dist\precache-manifest.c2ceeb313d877b1be5819d576f84fa8a.js | 4,93 KiB | 1,78 KiB
dist\service-worker.js | 0,95 KiB | 0,54 KiB

![image](https://user-images.githubusercontent.com/6383287/93639002-9974dd80-f9f8-11ea-95e0-d43338e72f2d.png)

**Comment by literakl** [comment]
There were side effects - some Vue components stopped working. Removed.
