### ISSUE TITLE
TipTap editor

### ISSUE THREAD

**Issue by literakl** [literakl/mezinamiridici#99]
this layout for blogs/articles: https://tinymce.github.io/tinymce-demos/templates-and-layout/locked-down-template-inline-fixed-toolbar.html

Trouble is an image upload. Is there Open Source pluging? Pictures must be stored on server and referenced via URL in the posts.

May help: 
https://www.tiny.cloud/docs-4x/configure/file-image-upload/
https://www.tiny.cloud/docs-4x/general-configuration-guide/upload-images/
https://stackoverflow.com/questions/50146834/how-to-upload-image-using-tinymce-editor
https://github.com/francoisjacquet/tinymce-uploadimage

**Comment by kotte-sanya** [comment]
Replaced editor.js to Tiptap editor.

**Comment by literakl** [comment]
It looks good. I have fine tuned the menu.
Problems:

- link button is missing
- Focus in blog is not displayed https://tiptap.dev/focus
- comments: integrate close and emoticons buttons into menu, close at right

**Comment by kotte-sanya** [comment]
Fixed all for issues mentioned above .

**Comment by literakl** [comment]
Please add this editor to Create and Edit Page with full page width. There shall be these menu items:

- undo
- redo
- bold
- italic
- underline
- headers h1-h3 (menu, if possible)
- bullet list
- numbered list
- tables
- link
- picture (upload)

**Comment by literakl** [comment]
List of user supplied components: https://github.com/ueberdosis/tiptap/issues/819

Discussion:

I will need a component to enter URL as new section with preview for twitter, youtube, instagram and facebook. Other URLs will be rendered as a box. There must be such component.

**Comment by kotte-sanya** [comment]
Added tiptap editor in Edit page and Create page.
Also have fixed image upload issue too.

**Comment by literakl** [comment]
thanks
